name: chassis_settings
name_cased: chassisSettings
category: chassis

identifier:
  msb: 0x00
  lsb: 0x53

api:
  intro: 5
  update: 11

getters:
  name: get_chassis_settings

setters:
  - name: set_driving_mode
    mandatory: [0x01]
  - name: start_stop_sports_chrono
    mandatory: [0x02]
  - name: set_spring_rates
    mandatory: [0x05]
  - name: set_chassis_position
    mandatory: [0x08]

state: all

properties:
  - id: 0x01
    name: driving_mode
    name_cased: drivingMode
    type: types.driving_mode
  - id: 0x02
    name: sport_chrono
    name_cased: sportChrono
    type: enum
    size: 1
    enum_values:
      - id: 0x00
        name: inactive
        verb: stop
      - id: 0x01
        name: active
        verb: start
      - id: 0x02
        name: reset
  - id: 0x05
    name: current_spring_rates
    name_cased: currentSpringRates
    type: types.spring_rate
    multiple: true
    description: The current values for the spring rates
  - id: 0x06
    name: maximum_spring_rates
    name_cased: maximumSpringRates
    type: types.spring_rate
    multiple: true
    description: The maximum possible values for the spring rates
  - id: 0x07
    name: minimum_spring_rates
    name_cased: minimumSpringRates
    type: types.spring_rate
    multiple: true
    description: The minimum possible values for the spring rates
  - id: 0x08
    name: current_chassis_position
    name_cased: currentChassisPosition
    type: integer
    size: 1
    description: The chassis position in mm calculated from the lowest point
  - id: 0x09
    name: maximum_chassis_position
    name_cased: maximumChassisPosition
    type: integer
    size: 1
    descrition: The maximum possible value for the chassis position
  - id: 0x0a
    name: minimum_chassis_position
    name_cased: minimumChassisPosition
    type: integer
    size: 1
    description: The minimum possible value for the chassis position
