name: chassis_settings
category: chassis

identifier:
    msb: 0x00
    lsb: 0x53

api:
    intro: 5
    update: 11

getters:
    default:
        omit_state_text: true

setters:
  - name: set_driving_mode
    mandatory: [0x01]
  - name: start_stop_sports_chrono
    mandatory: [0x02]
  - name: set_spring_rates
    mandatory: [0x05]
  - name: set_chassis_position
    mandatory: [0x08]

state: all

properties:
  - id: 0x01
    name: driving_mode
    type: enum
    size: 1
    values:
      - id: 0x00
        name: regular
      - id: 0x01
        name: eco
      - id: 0x02
        name: sport
      - id: 0x03
        name: sport_plus
      - id: 0x04
        name: ecoPlus
      - id: 0x05
        name: comfort
  - id: 0x02
    name: sport_chrono
    type: enum
    size: 1
    values:
      - id: 0x00
        name: inactive
        verb: stop
      - id: 0x01
        name: active
        verb: start
      - id: 0x02
        name: reset
  - id: 0x05
    name: current_spring_rates
    type: custom
    size: 2
    multiple: true
    items:
      - name: axle
        type: enum
        size: 1
        values:
          - id: 0x00
            name: front_axle
          - id: 0x01
            name: rear_axle
      - name: value
        type: uinteger
        size: 1
        description: The suspension spring rate in N/mm
  - id: 0x06
    name: maximum_spring_rates
    type: custom
    size: 2
    multiple: true
    items:
      - name: axle
        type: enum
        size: 1
        values:
          - id: 0x00
            name: front_axle
          - id: 0x01
            name: rear_axle
      - name: value
        type: uinteger
        size: 1
        description: The maximum possible value for the spring rate
  - id: 0x07
    name: minimum_spring_rates
    type: custom
    size: 2
    multiple: true
    items:
      - name: axle
        type: enum
        size: 1
        values:
          - id: 0x00
            name: front_axle
          - id: 0x01
            name: rear_axle
      - name: value
        type: uinteger
        size: 1
        description: The minimum possible value for the spring rate
  - id: 0x08
    name: current_chassis_position
    type: integer
    size: 1
    description: The chassis position in mm calculated from the lowest point
  - id: 0x09
    name: maximum_chassis_position
    type: integer
    size: 1
    descrition: The maximum possible value for the chassis position
  - id: 0x0A
    name: minimum_chassis_position
    type: integer
    size: 1
    description: The minimum possible value for the chassis position
