name: chassis_settings
name_cased: chassisSettings
name_pretty: Chassis Settings
category: chassis
authorization: true

identifier:
  msb: 0x00
  lsb: 0x53

api:
  intro: 5
  update: 11

getters:
  name: get_chassis_settings

setters:
  - name: set_driving_mode
    mandatory: [0x01]
    description: Set the driving mode.
  - name: start_stop_sports_chrono
    mandatory: [0x02]
    description: Start/Stop sport chrono.
  - name: set_spring_rates
    mandatory: [0x05]
    description: Set the spring rates.
  - name: set_chassis_position
    mandatory: [0x08]
    description: Set the chassis position.

state: all

properties:
  - id: 0x01
    name: driving_mode
    name_cased: drivingMode
    name_pretty: Driving mode
    type: types.driving_mode
    examples:
      - data_component: '01'
        value: 'eco'
        description: Driving mode is set to ECO
  - id: 0x02
    name: sport_chrono
    name_cased: sportChrono
    name_pretty: Sport chrono
    type: enum
    size: 1
    enum_values:
      - id: 0x00
        name: inactive
        verb: stop
      - id: 0x01
        name: active
        verb: start
      - id: 0x02
        name: reset
    examples:
      - data_component: '01'
        value: 'active'
        description: Sport Chrono is active
  - id: 0x05
    name: current_spring_rates
    name_cased: currentSpringRates
    name_pretty: Current spring rates
    type: types.spring_rate
    multiple: true
    name_singular: current_spring_rate
    description: The current values for the spring rates
    examples:
      - data_component: '4035000000000000'
        unit_component: '1801'
        values:
          axle: 'front'
          spring_rate: 21.0
        unit: newton_millimeters
        description: Front axle spring rate is 21.0N/mm
      - data_component: '4037000000000000'
        unit_component: '1801'
        values:
          axle: 'rear'
          spring_rate: 23.0
        unit: newton_millimeters
        description: Rear axle spring rate is 23.0N/mm
  - id: 0x06
    name: maximum_spring_rates
    name_cased: maximumSpringRates
    name_pretty: Maximum spring rates
    type: types.spring_rate
    multiple: true
    name_singular: maximum_spring_rate
    description: The maximum possible values for the spring rates
    examples:
      - data_component: '4042800000000000'
        unit_component: '1801'
        values:
          axle: 'front'
          spring_rate: 37.0
        unit: newton_millimeters
        description: Front axle maximum spring rate is 37.0N/mm
      - data_component: '4043800000000000'
        unit_component: '1801'
        values:
          axle: 'rear'
          spring_rate: 39.0
        unit: newton_millimeters
        description: Rear axle maximum spring rate is 39.0N/mm
  - id: 0x07
    name: minimum_spring_rates
    name_cased: minimumSpringRates
    name_pretty: Minimum spring rates
    type: types.spring_rate
    multiple: true
    name_singular: minimum_spring_rate
    description: The minimum possible values for the spring rates
    examples:
      - data_component: '4030000000000000'
        unit_component: '1801'
        values:
          axle: 'front'
          spring_rate: 16.0
        unit: newton_millimeters
        description: Front axle minimum spring rate is 16.0N/mm
      - data_component: '4032000000000000'
        unit_component: '1801'
        values:
          axle: 'rear'
          spring_rate: 18.0
        unit: newton_millimeters
        description: Rear axle minimum spring rate is 18.0N/mm
  - id: 0x08
    name: current_chassis_position
    name_cased: currentChassisPosition
    name_pretty: Current chassis position
    unit_type: length
    type: double
    size: 8
    description: The chassis position calculated from the lowest point
    examples:
      - data_component: '4039666666666666'
        unit_component: '1107'
        value: 25.4
        unit: millimeters
        description: Current chassis position is 25.4mm
  - id: 0x09
    name: maximum_chassis_position
    name_cased: maximumChassisPosition
    name_pretty: Maximum chassis position
    unit_type: length
    type: double
    size: 8
    description: The maximum possible value for the chassis position
    examples:
      - data_component: '404bc00000000000'
        unit_component: '1107'
        value: 55.5
        unit: millimeters
        description: Maximum chassis position is 55.5mm
  - id: 0x0a
    name: minimum_chassis_position
    name_cased: minimumChassisPosition
    name_pretty: Minimum chassis position
    unit_type: length
    type: double
    size: 8
    description: The minimum possible value for the chassis position
    examples:
      - data_component: 'c03c666666666666'
        unit_component: '1107'
        value: -28.4
        unit: millimeters
        description: Minimum chassis position is -28.4mm
